[Unit]
Before=systemd-vconsole-setup.service
After=systemd-readahead-drop.service
Type=oneshot
ExecStart=
StandardInput=tty
StandardOutput=tty

[Service]
ExecStart=/usr/bin/agetty --autologin root --noclear %I 38400 linux
